### ISSUE TITLE
Possible to get a C version?

### ISSUE THREAD

**Issue by aamlani** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#13]
Hi! Thanks for creating this! Just today I started using Visual Studio Code after having used Sublime for years. I really like the default Sublime theme, so this is great to have. I was wondering if it would be possible to get a version for C? I've switched the colorizer to your C# one, and it's way better than the standard one, but obviously not perfect.
Thanks regardless of whether or not this is something you can support.

**Comment by maximetinu** [comment]
Hi, I'm glad you like it 🙂 I made it for personal use but end up posting it because many of the other Monokai themes share the Monokai color scheme but not the one from Sublime specifically.

From what I remember, for matching the exact Sublime setup it needed the theme and the language colorizer. I only made it for C#, so it'll need a C colorizer to work for C. That'd be a matter of adding a file like theme-sublime-monokai-csharp-colorizer/syntaxes/[csharp.tmLanguage.json](https://github.com/Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code/blob/development/theme-sublime-monokai-csharp-colorizer/syntaxes/csharp.tmLanguage.json) but for C instead, based on the C default one [c.tmLanguage.json](https://github.com/microsoft/vscode/blob/main/extensions/cpp/syntaxes/c.tmLanguage.json) found at VS Code repo.

I'm not doing any support or maintenance to the project though, I'd like to come back to it someday and fix some of the C# errors, and eventually add support for some of the most known languages, but I don't have the time for now. If you feel like it, feel free to fork the repo, adding it, and opening a Pull Request 🙂

**Comment by aamlani** [comment]
Thanks for pointing me in the right direction! When I get some time, maybe I can get to it.

**Comment by maximetinu** [comment]
@aamlani You'll be happy to know that I've just published a new version with additional support for C, C++ and Python :) You can download it now [from the VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=maximetinu.identical-sublime-monokai-csharp-theme-colorizer).

**Comment by aamlani** [comment]
@Maximetinu You're the man! :)
