### ISSUE TITLE
File highlight in file explorer

### ISSUE THREAD

**Issue by aakbar5** [Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code#15]
In the latest vscode (1.56.0), file highlighter in greyish. How can it be fixed?
![Screenshot from 2021-05-09 09-59-55](https://user-images.githubusercontent.com/16612387/117566718-4303fe80-b0b0-11eb-9ae4-039a2d7af7af.png)

**Comment by maximetinu** [comment]
Hi, thanks for reporting it! It's also happening on the [default Monokai theme](https://github.com/microsoft/vscode/blob/main/extensions/theme-monokai/themes/monokai-color-theme.json), so I inherited that bug from there. It has to be some background color found at the first "colors" section of [themes/sublime-monokai-color-theme.json ](https://github.com/Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code/blob/master/themes/sublime-monokai-color-theme.json)

I can fix it on my side nonetheless. You could also verify that you have the same problem in the official Monokai and report it to the VSCode repository too.

Are you interested in fixing it yourself and open a PR to contribute? If so, you can find your local copy at: `C/Users/<yourusername>/.vscode/extensions/maximetinu.identical-sublime-monokai-csharp-theme-colorizer-1.0.1`

(Otherwise, I can take a look and fix it later today, or tomorrow at the latest. Cheers! 😁)

**Comment by maximetinu** [comment]
Update: I finally fixed it myself at [(229bf1c](https://github.com/Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code/commit/229bf1c332aee50f7740ceeb3f477a1fa36f5119) was an easy one 😋) And in the process I tried a feature of git I never used before: I made you co-author of the commit, so you're now an official contributor (how cool that is? 😂)

Thanks!

**Comment by aakbar5** [comment]
Thanks for the quick response.
